import { escapeHtml } from "./resume-doc";
import type { TailorResult } from "./partial-json";

export function renderMatchReportHtml(
  result: TailorResult,
  meta: { role: string; tone: string; when: string },
): string {
  const list = (items: string[]) =>
    items.length
      ? `<ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`
      : `<p class="empty">Nothing flagged.</p>`;

  const fixes = result.keyword_fixes.length
    ? `<table>
        <thead><tr><th>Keyword</th><th>In your resume</th><th>Suggested wording</th></tr></thead>
        <tbody>${result.keyword_fixes
          .map(
            (fix) =>
              `<tr><td class="kw">${escapeHtml(fix.keyword)}</td><td>${escapeHtml(
                fix.original_snippet || "—",
              )}</td><td>${escapeHtml(fix.suggestion)}</td></tr>`,
          )
          .join("")}</tbody></table>`
    : `<p class="empty">No wording swaps suggested.</p>`;

  return `<!doctype html>
<html><head><meta charset="utf-8" /><title>Match report</title>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600&family=Inter+Tight:wght@400;500;600&display=swap" />
<style>
  @page { size: Letter; margin: 0; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: 'Inter Tight', Helvetica, sans-serif; color: #1e1b18; font-size: 10.8pt; line-height: 1.55;
    -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  .page { width: 8.5in; min-height: 11in; margin: 0 auto; padding: 0.7in; }
  h1 { font-family: 'Fraunces', Georgia, serif; font-size: 24pt; margin: 0; }
  .meta { color: #6b625c; font-size: 9.5pt; margin-top: 6px; }
  h2 { font-size: 10.5pt; text-transform: uppercase; letter-spacing: 0.14em; color: #8a3d24; margin: 26px 0 8px; }
  .score { display: flex; align-items: baseline; gap: 10px; margin-top: 22px; }
  .score b { font-family: 'Fraunces', Georgia, serif; font-size: 40pt; line-height: 1; color: #8a3d24; }
  .bar { height: 9px; border-radius: 99px; background: #eae2db; overflow: hidden; margin-top: 12px; }
  .bar div { height: 100%; background: #8a3d24; }
  ul { margin: 0; padding-left: 18px; }
  li { margin-bottom: 5px; }
  .chips span { display: inline-block; border: 1px solid #ddd2c8; border-radius: 99px; padding: 3px 10px; margin: 0 6px 6px 0; font-size: 9.5pt; }
  table { width: 100%; border-collapse: collapse; font-size: 9.6pt; }
  th { text-align: left; border-bottom: 2px solid #ddd2c8; padding: 6px 8px 6px 0; color: #6b625c; font-weight: 600; }
  td { border-bottom: 1px solid #eee6df; padding: 7px 8px 7px 0; vertical-align: top; }
  td.kw { font-weight: 600; white-space: nowrap; }
  .empty { color: #6b625c; }
  footer { margin-top: 34px; color: #93887f; font-size: 8.8pt; border-top: 1px solid #eee6df; padding-top: 10px; }
</style></head>
<body><div class="page">
  <h1>Match report</h1>
  <p class="meta">${escapeHtml(meta.role)} &nbsp;•&nbsp; ${escapeHtml(meta.tone)} tone &nbsp;•&nbsp; ${escapeHtml(meta.when)}</p>
  <div class="score"><b>${result.match_score}</b><span>out of 100 fit with this posting</span></div>
  <div class="bar"><div style="width:${result.match_score}%"></div></div>
  <h2>What changed</h2>${list(result.changes)}
  <h2>Missing keywords</h2>
  ${
    result.missing_keywords.length
      ? `<div class="chips">${result.missing_keywords.map((k) => `<span>${escapeHtml(k)}</span>`).join("")}</div>`
      : `<p class="empty">Your resume already covers the posting's key terms.</p>`
  }
  <h2>Suggested wording swaps</h2>${fixes}
  <footer>Generated by Resume Tailor. Nothing you paste is stored on a server.</footer>
</div></body></html>`;
}
